tasks:
  # - name: 'Update models'
  #   file_glob: './src/pet_store/**/*cr'
  #   changes:
  #     -
  #       name: 'Correct AnyType?'
  #       pattern: 'JSONAny'
  #       new_value: 'JSON::Any'
  #     -
  #       name: 'Correct AnyType?'
  #       pattern: 'JSONType?'
  #       new_value: 'JSON::Type'
  #     -
  #       name: 'Correct AnyType?'
  #       pattern: 'JSONType'
  #       new_value: 'JSON::Type'
  - name: 'Update all'
    file_glob: './src/pet_store/**/*cr'
    changes:
      -
        name: "Remove empty if blocks"
        pattern: '(^\s+if [^\s]+ = [^\s]+$\n^\s+end$|^\s+if [^\s]+$\n^\s+end$)'
        new_value: ''
        multi_line: true
      -
        name: "Remove empty unless blocks"
        pattern: '(^\s+unless [^\s]+ = [^\s]+$\n^\s+end$|^\s+unless [^\s]+$\n^\s+end$)'
        new_value: ''
        multi_line: true
