tasks:
  - name: 'Update models'
    file_glob: './src/pet_store/models/*cr'
    changes:
      -
        name: 'Correct AnyType?'
        pattern: 'JSONAny'
        new_value: 'JSON::Any'
      -
        name: 'Correct AnyType?'
        pattern: 'JSONType?'
        new_value: 'JSON::Type'
      -
        name: 'Correct AnyType?'
        pattern: 'JSONType'
        new_value: 'JSON::Type'
      -
        name: "Remove empty if blocks"
        pattern: '^\s+if _[^\s]+ = [^\s]+$\n^\s+end$'
        new_value: ''
        multi_line: true
