tasks:
  - name: 'Update models'
    file_glob: './src/pet_store/models/*cr'
    changes:
      -
        name: 'Correct AnyType?'
        pattern: 'JSONAny\?'
        new_value: 'JSON::Any'
      -
        name: 'Correct AnyType?'
        pattern: 'JSONAny'
        new_value: 'JSON::Any'
