#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for PetStore::AdditionalPropertiesClass
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/pet_store/models/additional_properties_class"

describe PetStore::AdditionalPropertiesClass do
  describe "test an instance of AdditionalPropertiesClass" do
    it "should create an instance of AdditionalPropertiesClass" do
      # instance = PetStore::AdditionalPropertiesClass.new
      # (instance).should be_a(PetStore::AdditionalPropertiesClass)
    end
  end

  describe "test attribute 'map_property'" do
    it "should work" do
      # instance = PetStore::AdditionalPropertiesClass.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'map_of_map_property'" do
    it "should work" do
      # instance = PetStore::AdditionalPropertiesClass.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
