#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for PetStore::Animal
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PetStore::Animal do
  describe "test an instance of Animal" do
    it "should create an instance of Animal" do
      # instance = PetStore::Animal.new
      # (instance).should be_a(PetStore::Animal)
    end
  end

  describe "#hash" do
    context "color_preset is different" do
      it "returns false" do
        json = %({"className":"animal","color":"red"})
        animal1 = PetStore::Animal.from_json(json)
        animal2 = PetStore::Animal.from_json(json)
        (animal1 == animal2).should be_true
        (animal1.hash).should eq(animal2.hash)
        animal2.color_present = false
        (animal1.color_present?).should_not eq(animal2.color_present?)
        (animal1.hash).should_not eq(animal2.hash)
        (animal1 == animal2).should be_false
      end
    end
  end

  describe "test attribute 'class_name'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'color'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
