#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for PetStore::AppleReq
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/pet_store/models/apple_req"

describe PetStore::AppleReq do
  describe "test an instance of AppleReq" do
    it "should create an instance of AppleReq" do
      # instance = PetStore::AppleReq.new
      # (instance).should be_a(PetStore::AppleReq)
    end
  end

  describe "test attribute 'cultivar'" do
    it "should work" do
      # instance = PetStore::AppleReq.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'mealy'" do
    it "should work" do
      # instance = PetStore::AppleReq.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
