#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for PetStore::DogAllOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/pet_store/models/dog_all_of"

describe PetStore::DogAllOf do
  describe "test an instance of DogAllOf" do
    it "should create an instance of DogAllOf" do
      # instance = PetStore::DogAllOf.new
      # (instance).should be_a(PetStore::DogAllOf)
    end
  end

  describe "test attribute 'breed'" do
    it "should work" do
      # instance = PetStore::DogAllOf.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
