#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for PetStore::EnumClass
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PetStore::EnumClass do
  describe "test an instance of EnumClass" do
    it "should create an instance of EnumClass" do
      # instance = PetStore::EnumClass.new
      # expect(instance).to be_instance_of(PetStore::EnumClass)
    end
  end
end
