#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for PetStore::List
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/pet_store/models/list"

describe PetStore::List do
  describe "test an instance of List" do
    it "should create an instance of List" do
      # instance = PetStore::List.new
      # (instance).should be_a(PetStore::List)
    end
  end

  describe "test attribute '_123_list'" do
    it "should work" do
      # instance = PetStore::List.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
