#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for PetStore::MapTest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PetStore::MapTest do
  describe "test an instance of MapTest" do
    it "should create an instance of MapTest" do
      # instance = PetStore::MapTest.new
      # expect(instance).to be_instance_of(PetStore::MapTest)
    end
  end

  describe "test attribute 'map_map_of_string'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'map_of_enum_string'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
      # validator = EnumValidator.new("Hash(String, String)", ["UPPER", "lower"])
      # validator.allowable_values.each do |value|
      #   expect { instance.map_of_enum_string = value }.not_to raise_error
      # end
    end
  end

  describe "test attribute 'direct_map'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'indirect_map'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
