#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for PetStore::MixedPropertiesAndAdditionalPropertiesClass
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PetStore::MixedPropertiesAndAdditionalPropertiesClass do
  describe "test an instance of MixedPropertiesAndAdditionalPropertiesClass" do
    it "should create an instance of MixedPropertiesAndAdditionalPropertiesClass" do
      # instance = PetStore::MixedPropertiesAndAdditionalPropertiesClass.new
      # (instance).should be_a(PetStore::MixedPropertiesAndAdditionalPropertiesClass)
    end
  end

  describe "test attribute 'uuid'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'date_time'" do
    it "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'map'" do
    it "validates attribute 'map'" do
      animal = PetStore::Animal.new
      map = {"dog" => animal}
      parent = PetStore::MixedPropertiesAndAdditionalPropertiesClass.new
      parent.valid?.should be_true
      parent.list_invalid_properties.empty?.should be_true
      expect_raises(Exception, "PetStore::Animal is invalid") do
        parent.map = map
      end
      parent2 = PetStore::MixedPropertiesAndAdditionalPropertiesClass.new(map: map)
      parent2.valid?.should be_false
      parent2.list_invalid_properties.should eq(["map: \"class_name\" is required and cannot be null"])
    end
  end
end
