#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for PetStore::NumberOnly
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/pet_store/models/number_only"

describe PetStore::NumberOnly do
  describe "test an instance of NumberOnly" do
    it "should create an instance of NumberOnly" do
      # instance = PetStore::NumberOnly.new
      # (instance).should be_a(PetStore::NumberOnly)
    end
  end

  describe "test attribute 'just_number'" do
    it "should work" do
      # instance = PetStore::NumberOnly.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
