#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for PetStore::OuterEnumRquiredInt64
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/pet_store/models/outer_enum_rquired_int64"

describe PetStore::OuterEnumRquiredInt64 do
  describe "test an instance of OuterEnumRquiredInt64" do
    it "should create an instance of OuterEnumRquiredInt64" do
      # instance = PetStore::OuterEnumRquiredInt64.new
      # (instance).should be_a(PetStore::OuterEnumRquiredInt64)
    end
  end
end
