#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

require "../spec_helper"

# Unit tests for PetStore::OuterEnumInteger
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PetStore::OuterEnumInteger do
  describe "test an instance of OuterEnumInteger" do
    it "should create an instance of OuterEnumInteger" do
      # instance = PetStore::OuterEnumInteger.new
      # (instance).should be_a(PetStore::OuterEnumInteger)
    end
  end
end
