#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for PetStore::OuterComposite
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/pet_store/models/outer_composite"

describe PetStore::OuterComposite do
  describe "test an instance of OuterComposite" do
    it "should create an instance of OuterComposite" do
      # instance = PetStore::OuterComposite.new
      # (instance).should be_a(PetStore::OuterComposite)
    end
  end

  describe "test attribute 'my_number'" do
    it "should work" do
      # instance = PetStore::OuterComposite.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'my_string'" do
    it "should work" do
      # instance = PetStore::OuterComposite.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'my_boolean'" do
    it "should work" do
      # instance = PetStore::OuterComposite.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
