#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

# Unit tests for PetStore::TestEndpointParametersRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
require "../spec_helper"
require "../../src/pet_store/models/test_endpoint_parameters_request"

describe PetStore::TestEndpointParametersRequest do
  describe "test an instance of TestEndpointParametersRequest" do
    it "should create an instance of TestEndpointParametersRequest" do
      # instance = PetStore::TestEndpointParametersRequest.new
      # (instance).should be_a(PetStore::TestEndpointParametersRequest)
    end
  end

  describe "test attribute 'integer'" do
    it "should work" do
      # instance = PetStore::TestEndpointParametersRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'int32'" do
    it "should work" do
      # instance = PetStore::TestEndpointParametersRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'int64'" do
    it "should work" do
      # instance = PetStore::TestEndpointParametersRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'number'" do
    it "should work" do
      # instance = PetStore::TestEndpointParametersRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'float'" do
    it "should work" do
      # instance = PetStore::TestEndpointParametersRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'double'" do
    it "should work" do
      # instance = PetStore::TestEndpointParametersRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'string'" do
    it "should work" do
      # instance = PetStore::TestEndpointParametersRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'pattern_without_delimiter'" do
    it "should work" do
      # instance = PetStore::TestEndpointParametersRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'byte'" do
    it "should work" do
      # instance = PetStore::TestEndpointParametersRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'binary'" do
    it "should work" do
      # instance = PetStore::TestEndpointParametersRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'date'" do
    it "should work" do
      # instance = PetStore::TestEndpointParametersRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'date_time'" do
    it "should work" do
      # instance = PetStore::TestEndpointParametersRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'password'" do
    it "should work" do
      # instance = PetStore::TestEndpointParametersRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'callback'" do
    it "should work" do
      # instance = PetStore::TestEndpointParametersRequest.new
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end
end
