#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module PetStore
  @[JSON::Serializable::Options(emit_nulls: true)]
  class HasOnlyReadOnly
    include JSON::Serializable
    include JSON::Serializable::Unmapped

    # Optional properties

    @[JSON::Field(key: "bar", type: String?, default: nil, presence: true, ignore_serialize: bar.nil? && !bar_present?)]
    getter bar : String? = nil

    @[JSON::Field(ignore: true)]
    property? bar_present : Bool = false

    @[JSON::Field(key: "foo", type: String?, default: nil, presence: true, ignore_serialize: foo.nil? && !foo_present?)]
    getter foo : String? = nil

    @[JSON::Field(ignore: true)]
    property? foo_present : Bool = false

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @bar : String? = nil,
      @foo : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] bar Object to be assigned
    def bar=(bar : String?)
      if bar.nil?
        @bar_present = false
        return @bar = nil
      end
      @bar = bar
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] foo Object to be assigned
    def foo=(foo : String?)
      if foo.nil?
        @foo_present = false
        return @foo = nil
      end
      @foo = foo
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@bar, @bar_present, @foo, @foo_present)
  end
end
