#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

require "../../core"

module PetStore
  class MapTest
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Optional Properties

    @[JSON::Field(key: "map_map_of_string", type: Hash(String, Hash(String, String))?, default: nil, required: false, nullable: false, emit_null: false)]
    getter map_map_of_string : Hash(String, Hash(String, String))? = nil

    @[JSON::Field(key: "map_of_enum_string", type: Hash(String, String)?, default: nil, required: false, nullable: false, emit_null: false)]
    getter map_of_enum_string : Hash(String, String)? = nil
    ERROR_MESSAGE_FOR_MAP_OF_ENUM_STRING = "invalid value for \"map_of_enum_string\", must be one of [UPPER, lower]."
    VALID_VALUES_FOR_MAP_OF_ENUM_STRING  = String.static_array("UPPER", "lower")

    @[JSON::Field(key: "direct_map", type: Hash(String, Bool)?, default: nil, required: false, nullable: false, emit_null: false)]
    getter direct_map : Hash(String, Bool)? = nil

    @[JSON::Field(key: "indirect_map", type: Hash(String, Bool)?, default: nil, required: false, nullable: false, emit_null: false)]
    getter indirect_map : Hash(String, Bool)? = nil

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @map_map_of_string : Hash(String, Hash(String, String))? = nil,
      @map_of_enum_string : Hash(String, String)? = nil,
      @direct_map : Hash(String, Bool)? = nil,
      @indirect_map : Hash(String, Bool)? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      unless (_map_of_enum_string = @map_of_enum_string).nil?
        invalid_properties.push(ERROR_MESSAGE_FOR_MAP_OF_ENUM_STRING) unless OpenApi::EnumValidator.valid?(_map_of_enum_string, VALID_VALUES_FOR_MAP_OF_ENUM_STRING)
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool
      unless (_map_of_enum_string = @map_of_enum_string).nil?
        return false unless OpenApi::EnumValidator.valid?(_map_of_enum_string, VALID_VALUES_FOR_MAP_OF_ENUM_STRING)
      end

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] map_map_of_string Object to be assigned
    def map_map_of_string=(new_value : Hash(String, Hash(String, String))?)
      @map_map_of_string = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] map_of_enum_string Object to be assigned
    def map_of_enum_string=(new_value : Hash(String, String)?)
      unless new_value.nil?
        OpenApi::EnumValidator.validate("map_of_enum_string", new_value, VALID_VALUES_FOR_MAP_OF_ENUM_STRING)
      end

      @map_of_enum_string = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] direct_map Object to be assigned
    def direct_map=(new_value : Hash(String, Bool)?)
      @direct_map = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] indirect_map Object to be assigned
    def indirect_map=(new_value : Hash(String, Bool)?)
      @indirect_map = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@map_map_of_string, @map_of_enum_string, @direct_map, @indirect_map)
  end
end
