#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module PetStore
  @[JSON::Serializable::Options(emit_nulls: true)]
  class MixedPropertiesAndAdditionalPropertiesClass
    include JSON::Serializable
    include JSON::Serializable::Unmapped

    # Optional properties

    @[JSON::Field(key: "uuid", type: String?, presence: true, ignore_serialize: uuid.nil? && !uuid_present?)]
    property uuid : String?

    @[JSON::Field(ignore: true)]
    property? uuid_present : Bool = false

    @[JSON::Field(key: "dateTime", type: Time?, converter: Time::RFC3339Converter, presence: true, ignore_serialize: date_time.nil? && !date_time_present?)]
    property date_time : Time?

    @[JSON::Field(ignore: true)]
    property? date_time_present : Bool = false

    @[JSON::Field(key: "map", type: Hash(String, Animal)?, presence: true, ignore_serialize: map.nil? && !map_present?)]
    property map : Hash(String, Animal)?

    @[JSON::Field(ignore: true)]
    property? map_present : Bool = false

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @uuid : String? = nil,
      @date_time : Time? = nil,
      @map : Hash(String, Animal)? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@uuid, @uuid_present, @date_time, @date_time_present, @map, @map_present)
  end
end
