#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module PetStore
  # Model for testing model name same as property name
  class Name
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Json

    # Required properties

    @[JSON::Field(key: "name", type: Int32?, default: nil, required: true, nullable: false, emit_null: false)]
    getter name : Int32? = nil

    # Optional properties

    @[JSON::Field(key: "snake_case", type: Int32?, default: nil, required: false, nullable: false, emit_null: false)]
    getter snake_case : Int32? = nil

    @[JSON::Field(key: "property", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter property : String? = nil

    @[JSON::Field(key: "123Number", type: Int32?, default: nil, required: false, nullable: false, emit_null: false)]
    getter _123_number : Int32? = nil

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Required properties
      @name : Int32? = nil,
      # Optional properties
      @snake_case : Int32? = nil,
      @property : String? = nil,
      @_123_number : Int32? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties.push("\"name\" is required and cannot be null") if @name.nil?

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @name.nil?

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] name Object to be assigned
    def name=(name : Int32?)
      if name.nil?
        raise ArgumentError.new("\"name\" is required and cannot be null")
      end
      @name = name
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] snake_case Object to be assigned
    def snake_case=(snake_case : Int32?)
      if snake_case.nil?
        return @snake_case = nil
      end
      @snake_case = snake_case
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] property Object to be assigned
    def property=(property : String?)
      if property.nil?
        return @property = nil
      end
      @property = property
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] _123_number Object to be assigned
    def _123_number=(_123_number : Int32?)
      if _123_number.nil?
        return @_123_number = nil
      end
      @_123_number = _123_number
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@name, @snake_case, @property, @_123_number)
  end
end
