#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module PetStore
  # Model for testing model name same as property name
  @[JSON::Serializable::Options(emit_nulls: true)]
  class Name
    include JSON::Serializable
    include JSON::Serializable::Unmapped

    # Required properties

    @[JSON::Field(key: "name", type: Int32)]
    property name : Int32

    # Optional properties

    @[JSON::Field(key: "snake_case", type: Int32?, presence: true, ignore_serialize: snake_case.nil? && !snake_case_present?)]
    property snake_case : Int32?

    @[JSON::Field(ignore: true)]
    property? snake_case_present : Bool = false

    @[JSON::Field(key: "property", type: String?, presence: true, ignore_serialize: property.nil? && !property_present?)]
    property property : String?

    @[JSON::Field(ignore: true)]
    property? property_present : Bool = false

    @[JSON::Field(key: "123Number", type: Int32?, presence: true, ignore_serialize: _123_number.nil? && !_123_number_present?)]
    property _123_number : Int32?

    @[JSON::Field(ignore: true)]
    property? _123_number_present : Bool = false

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Required properties
      @name : Int32,
      # Optional properties
      @snake_case : Int32? = nil,
      @property : String? = nil,
      @_123_number : Int32? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@name, @snake_case, @property, @_123_number)
  end
end
