#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module PetStore
  @[JSON::Serializable::Options(emit_nulls: true)]
  class Order
    include JSON::Serializable
    include JSON::Serializable::Unmapped

    # Optional properties

    @[JSON::Field(key: "id", type: Int64?, default: nil, presence: true, ignore_serialize: id.nil? && !id_present?)]
    getter id : Int64? = nil

    @[JSON::Field(ignore: true)]
    property? id_present : Bool = false

    @[JSON::Field(key: "petId", type: Int64?, default: nil, presence: true, ignore_serialize: pet_id.nil? && !pet_id_present?)]
    getter pet_id : Int64? = nil

    @[JSON::Field(ignore: true)]
    property? pet_id_present : Bool = false

    @[JSON::Field(key: "quantity", type: Int32?, default: nil, presence: true, ignore_serialize: quantity.nil? && !quantity_present?)]
    getter quantity : Int32? = nil

    @[JSON::Field(ignore: true)]
    property? quantity_present : Bool = false

    @[JSON::Field(key: "shipDate", type: Time?, default: nil, presence: true, ignore_serialize: ship_date.nil? && !ship_date_present?, converter: Time::RFC3339Converter)]
    getter ship_date : Time? = nil

    @[JSON::Field(ignore: true)]
    property? ship_date_present : Bool = false

    # Order Status
    @[JSON::Field(key: "status", type: String?, default: nil, presence: true, ignore_serialize: status.nil? && !status_present?)]
    getter status : String? = nil

    @[JSON::Field(ignore: true)]
    property? status_present : Bool = false

    ENUM_VALIDATOR_FOR_STATUS = EnumValidator.new("status", "String", ["placed", "approved", "delivered"])

    @[JSON::Field(key: "complete", type: Bool?, default: false, presence: true, ignore_serialize: complete.nil? && !complete_present?)]
    getter complete : Bool? = false

    @[JSON::Field(ignore: true)]
    property? complete_present : Bool = false

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Optional properties
      @id : Int64? = nil,
      @pet_id : Int64? = nil,
      @quantity : Int32? = nil,
      @ship_date : Time? = nil,
      @status : String? = nil,
      @complete : Bool? = false
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new

      invalid_properties.push(ENUM_VALIDATOR_FOR_STATUS.error_message) unless ENUM_VALIDATOR_FOR_STATUS.valid?(@status)

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false unless ENUM_VALIDATOR_FOR_STATUS.valid?(@status)

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] id Object to be assigned
    def id=(id : Int64?)
      if id.nil?
        @id_present = false
        return @id = nil
      end
      @id = id
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] pet_id Object to be assigned
    def pet_id=(pet_id : Int64?)
      if pet_id.nil?
        @pet_id_present = false
        return @pet_id = nil
      end
      @pet_id = pet_id
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] quantity Object to be assigned
    def quantity=(quantity : Int32?)
      if quantity.nil?
        @quantity_present = false
        return @quantity = nil
      end
      @quantity = quantity
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] ship_date Object to be assigned
    def ship_date=(ship_date : Time?)
      if ship_date.nil?
        @ship_date_present = false
        return @ship_date = nil
      end
      @ship_date = ship_date
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status : String?)
      if status.nil?
        @status_present = false
        return @status = nil
      end
      _status = status.not_nil!
      ENUM_VALIDATOR_FOR_STATUS.valid!(_status)
      @status = status
    end # Custom attribute writer method checking allowed values (enum).
    # @param [Object] complete Object to be assigned
    def complete=(complete : Bool?)
      if complete.nil?
        @complete_present = false
        return @complete = nil
      end
      @complete = complete
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@id, @id_present, @pet_id, @pet_id_present, @quantity, @quantity_present, @ship_date, @ship_date_present, @status, @status_present, @complete, @complete_present)
  end
end
