#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module PetStore
  class OuterEnumIntegerDefaultValue
    include OpenApi::Validatable
    include OpenApi::Json

    property data : Int32

    ERROR_MESSAGE = %{invalid value for "OuterEnumIntegerDefaultValue", must be one of ["0", "1", "2"].}

    VALID_VALUES = Int32.static_array("0", "1", "2")

    delegate to_json_object_key, to: @data

    def self.from_json(value : JSON::PullParser) : OuterEnumIntegerDefaultValue
      new(value)
    end

    def self.to_json(value : OuterEnumIntegerDefaultValue, json : JSON::Builder) : Nil
      value.to_json(json)
    end

    def self.new(pull : JSON::PullParser)
      new(Int32.new(pull), false)
    end

    def self.from_json_object_key?(key : String)
      Int32.from_json_object_key?(key)
    end

    def initialize(@data : Int32, strict : Bool = true)
      validate if strict
    end

    def error_message : String
      ERROR_MESSAGE
    end

    def list_invalid_properties : Array(String)
      errors = Array(String).new
      errors.push(error_message) unless valid?
      errors
    end

    def valid? : Bool
      OpenApi::EnumValidator.valid?(data, VALID_VALUES, false)
    end

    def validate : Nil
      OpenApi::EnumValidator.validate("OuterEnumIntegerDefaultValue", data, VALID_VALUES, false)
    end

    def to_json(json : JSON::Builder) : Nil
      @data.to_json(json)
    end

    def_equals_and_hash(@data)
  end
end
