#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

require "json"
require "time"
require "log"

module PetStore
  class UploadFileWithRequiredFileRequest
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Required Properties

    # file to upload
    @[JSON::Field(key: "requiredFile", type: ::File?, default: nil, required: true, nullable: false, emit_null: false)]
    getter required_file : ::File? = nil

    # End of Required Properties

    # Optional Properties

    # Additional data to pass to server
    @[JSON::Field(key: "additionalMetadata", type: String?, default: nil, required: false, nullable: false, emit_null: false)]
    getter additional_metadata : String? = nil

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Required properties
      @required_file : ::File? = nil,
      # Optional properties
      @additional_metadata : String? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      invalid_properties.push("\"required_file\" is required and cannot be null") if @required_file.nil?

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool
      return false if @required_file.nil?

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] required_file Object to be assigned
    def required_file=(required_file : ::File?)
      if required_file.nil?
        raise ArgumentError.new("\"required_file\" is required and cannot be null")
      end
      _required_file = required_file.not_nil!
      @required_file = _required_file
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] additional_metadata Object to be assigned
    def additional_metadata=(additional_metadata : String?)
      if additional_metadata.nil?
        return @additional_metadata = nil
      end
      _additional_metadata = additional_metadata.not_nil!
      @additional_metadata = _additional_metadata
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@required_file, @additional_metadata)
  end
end
