#  OpenAPI Petstore
#
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech
#

require "../../core"

module PetStore
  class Whale
    include JSON::Serializable
    include JSON::Serializable::Unmapped
    include OpenApi::Validatable
    include OpenApi::Json

    # Required Properties

    @[JSON::Field(key: "className", type: String?, default: nil, required: true, nullable: false, emit_null: false)]
    getter class_name : String? = nil

    # End of Required Properties

    # Optional Properties

    @[JSON::Field(key: "hasBaleen", type: Bool?, default: nil, required: false, nullable: false, emit_null: false)]
    getter has_baleen : Bool? = nil

    @[JSON::Field(key: "hasTeeth", type: Bool?, default: nil, required: false, nullable: false, emit_null: false)]
    getter has_teeth : Bool? = nil

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(
      *,
      # Required properties
      @class_name : String? = nil,
      # Optional properties
      @has_baleen : Bool? = nil,
      @has_teeth : Bool? = nil
    )
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties : Array(String)
      invalid_properties = Array(String).new

      invalid_properties.push("\"class_name\" is required and cannot be null") if @class_name.nil?

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid? : Bool
      return false if @class_name.nil?

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] class_name Object to be assigned
    def class_name=(new_value : String?)
      raise ArgumentError.new("\"class_name\" is required and cannot be null") if new_value.nil?

      @class_name = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] has_baleen Object to be assigned
    def has_baleen=(new_value : Bool?)
      @has_baleen = new_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] has_teeth Object to be assigned
    def has_teeth=(new_value : Bool?)
      @has_teeth = new_value
    end

    # Generates #hash and #== methods from all fields
    # #== @return [Bool]
    # #hash calculates hash code according to all attributes.
    # #hash @return [UInt64] Hash code
    def_equals_and_hash(@class_name, @has_baleen, @has_teeth)
  end
end
